set_project("ferrofluid-3d")
set_languages("cxxlatest")

add_rules("mode.debug", "mode.release")

includes("SimViewer")
includes("cuda")

add_requires("amgcl")
add_requires("cxxopts v3.1.1")
add_requires("eigen")
add_requires("spdlog", { configs = { fmt_external = true } })
add_requires("openmp")
add_requires("tbb")
add_requires("yaml-cpp 0.7.0")

target("fmm")
    set_languages("c++11")
    set_kind("static")
    add_packages("openmp")

    add_includedirs("fmmtl/kernel")
    add_includedirs("fmmtl/fmmtl")
    add_includedirs("fmmtl")
    add_includedirs("thrust")
    add_headerfiles("fmmtl/fmmtl/*.hpp")
    add_headerfiles("fmmtl/kernel/*.hpp")
    add_files("fmmtl/*.cpp")

target("demo")
    set_kind("binary")
    add_deps("fmm")
    add_packages("amgcl")
    add_packages("cxxopts")
    add_packages("eigen")
    add_packages("spdlog")
    add_packages("openmp")
    add_packages("tbb")
    add_packages("yaml-cpp")

    add_includedirs("core")
    add_includedirs("MC-style-vol-eval")
    add_includedirs("fmmtl")
    add_headerfiles("core/**.h")
    add_files("core/**.cpp")
    add_cugencodes("native")
    add_headerfiles("demo/**.h")
    add_files("demo/**.cpp")
