option("cuda")
    set_default(false)
    set_showmenu(true)
    set_description("Build the CUDA runtime bootstrap targets (CUDA 12.8+ required).")
option_end()

target("cuda_host_tests")
    set_default(false)
    set_kind("binary")
    set_languages("cxx20")
    add_defines("PIVOT_CUDA_BOOTSTRAP_NOT_A_FLUID_SOLVER=1", { public = true })
    add_includedirs(".", { public = true })
    add_includedirs("core/grid", "core/scene")
    add_files("core/scene/PlaneScene.cpp")
    add_files("tests/host/PlaneSceneContractTest.cpp")

if has_config("cuda") then
    target("sim_cuda")
        set_default(false)
        set_kind("static")
        set_languages("cxx20")
        add_includedirs(".", { public = true })
        add_links("cudart", { public = true })
        add_cugencodes("sm_80", "sm_89", "sm_120", "compute_120")
        add_cuflags("--fmad=false")
        add_files("core/scene/PlaneScene.cpp")
        add_files("core/runtime/CudaContext.cu")
        add_files("core/scene/PlaneScene.cu")

    target("cuda_runtime_tests")
        set_default(false)
        set_kind("binary")
        set_languages("cxx20")
        add_deps("sim_cuda")
        add_includedirs(".")
        add_files("tests/runtime/PlaneInitializationTest.cu")
end
